sudo: required

services:
  - docker

matrix:
  include:
    - env: distribution=arch-latest
      os: linux
      language: cpp
    - env: distribution=ubuntu-18.04
      os: linux
      language: cpp

before_install:
  - docker build -t ${distribution} - < .ci/Dockerfile-${distribution}

script:
  - docker run --mount source=$(pwd),target=/app,type=bind -w /app ${distribution} /bin/bash -c ".ci/ci.sh"
